Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 200
Metrics/MethodLength:
  Max: 25
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/GlobalVars:
  Enabled: false